# _config.yml
# Título y descripción de tu sitio
title: "AoC Gamers Resources"
description: "Recursos para la comunidad de AoC Gamers"

# URL principal de tu sitio (dominio propio)
url: "https://resources.aoc-gamers.com"

# Si el sitio se sirve en la raíz, deja baseurl vacío. Si se sirve en un subdirectorio, indícalo aquí.
baseurl: ""

# Otras configuraciones (puedes agregar plugins, markdown, etc.)
markdown: kramdown
theme: minima
